# Generated by Django 3.2.3 on 2021-06-12 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cementcompressive',
            name='unique_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.newproject'),
        ),
        migrations.AlterField(
            model_name='cementconsistencytest',
            name='unique_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.newproject'),
        ),
        migrations.AlterField(
            model_name='cementsettingtime',
            name='unique_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.newproject'),
        ),
    ]
