# Generated by Django 3.0.6 on 2020-09-05 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cube_1_w', models.IntegerField()),
                ('cube_2_w', models.IntegerField()),
                ('cube_3_w', models.IntegerField()),
                ('cube_4_w', models.IntegerField()),
                ('cube_5_w', models.IntegerField()),
                ('cube_6_w', models.IntegerField()),
                ('cube_7_w', models.IntegerField()),
                ('cube_8_w', models.IntegerField()),
                ('cube_9_w', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
