# Generated by Django 3.0.6 on 2020-09-05 12:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cement',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
