# Generated by Django 3.0.6 on 2020-09-05 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200905_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='cement',
            name='test_number',
            field=models.IntegerField(default=0),
        ),
    ]
