# Generated by Django 3.0.6 on 2020-09-05 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_cement_test_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cement',
            name='test_number',
        ),
        migrations.AddField(
            model_name='cement',
            name='test_title',
            field=models.CharField(default='My Test 1', max_length=100),
        ),
    ]
